import type { AppState, MealTemplate } from "./models";

export const DEFAULT_MEALS: MealTemplate[] = [
  {
    id: "plenny-pro",
    name: "Plenny Shake Pro con agua fría",
    shortName: "Plenny Pro",
    kind: "breakfast",
    baseKcal: 400,
    baseProteinG: 40,
    baseFibreG: 7.5,
    baseGrams: 99,
    ingredients: [
      "99 g de Plenny Shake Pro",
      "500 ml de agua fría",
      "1 cucharadita de azúcar solo si la necesitas para poder tomarlo",
    ],
    instructions:
      "Deja el polvo medido la noche anterior. En el trabajo añade agua fría, agita y bébelo sin tener que montar la batidora.",
    tags: ["rápido", "alto en proteína", "despensa"],
    slots: ["breakfast", "snack", "dinner"],
    active: true,
  },
  {
    id: "plenny-half",
    name: "Media ración de Plenny Shake Pro",
    shortName: "½ Plenny",
    kind: "quick",
    baseKcal: 200,
    baseProteinG: 20,
    baseFibreG: 3.8,
    baseGrams: 50,
    ingredients: ["50 g de Plenny Shake Pro", "300–350 ml de agua o leche"],
    instructions: "Agita en un vaso mezclador. Úsalo como puente, no como castigo por otra comida.",
    tags: ["rápido", "alto en proteína", "despensa"],
    slots: ["breakfast", "snack", "dinner"],
    active: true,
  },
  {
    id: "tvp-beans-tomato",
    name: "Boloñesa de soja, beans y verduras escondidas",
    shortName: "Soja + beans",
    kind: "batch",
    baseKcal: 650,
    baseProteinG: 43,
    baseFibreG: 18,
    baseGrams: 520,
    ingredients: [
      "soja texturizada",
      "alubias o judías",
      "tomate cocinado",
      "zanahoria, calabacín y champiñón triturados",
      "pasta o arroz según el día",
      "queso al servir",
    ],
    instructions:
      "Haz una olla para cuatro días. Congela dos días en porciones y guarda dos en nevera. Cocina el arroz o la pasta aparte para poder variar.",
    tags: ["batch", "beans", "mucha fibra", "verdura escondida"],
    slots: ["lunch", "dinner"],
    active: true,
  },
  {
    id: "tofu-pea-curry",
    name: "Curry cremoso de tofu, guisantes y calabaza",
    shortName: "Curry de tofu",
    kind: "batch",
    baseKcal: 600,
    baseProteinG: 36,
    baseFibreG: 14,
    baseGrams: 500,
    ingredients: [
      "tofu dorado",
      "guisantes",
      "calabaza o zanahoria triturada",
      "leche de coco ligera o yogur",
      "curry suave para Rali; picante extra al servir",
      "arroz o fideos aparte",
    ],
    instructions:
      "Tritura la base vegetal, añade tofu dorado y guisantes. Congela la salsa en cubos o porciones; el arroz puede ser congelado de emergencia.",
    tags: ["batch", "cremoso", "verdura escondida", "congelable"],
    slots: ["lunch", "dinner"],
    active: true,
  },
  {
    id: "lentil-stew",
    name: "Guiso de lentejas con verduras trituradas",
    shortName: "Lentejas",
    kind: "batch",
    baseKcal: 580,
    baseProteinG: 32,
    baseFibreG: 21,
    baseGrams: 560,
    ingredients: [
      "lentejas",
      "zanahoria, calabacín y champiñón triturados",
      "tomate cocinado",
      "patata o arroz",
      "huevo o queso como extra opcional",
    ],
    instructions: "Cuece una olla espesa. Congela en monodosis y añade el extra proteico al recalentar.",
    tags: ["batch", "beans", "mucha fibra", "congelable"],
    slots: ["lunch", "dinner"],
    active: true,
  },
  {
    id: "eggs-beans-cheese",
    name: "Huevos, beans, pan y queso",
    shortName: "Huevos + beans",
    kind: "emergency",
    baseKcal: 610,
    baseProteinG: 36,
    baseFibreG: 16,
    baseGrams: 470,
    ingredients: ["2 huevos", "200 g de beans", "60 g de pan", "20 g de queso"],
    instructions:
      "Calienta los beans mientras haces los huevos. Si hay crema de verduras congelada, úsala como entrante. La siguiente comida vuelve al plan normal.",
    tags: ["10 minutos", "emergencia", "beans", "queso"],
    slots: ["lunch", "dinner"],
    active: true,
  },
  {
    id: "buldak-upgraded",
    name: "Buldak mejorado con tofu, huevo y guisantes",
    shortName: "Buldak completo",
    kind: "quick",
    baseKcal: 790,
    baseProteinG: 38,
    baseFibreG: 10,
    baseGrams: 520,
    ingredients: ["1 paquete de buldak", "tofu crujiente", "1 huevo", "guisantes", "queso opcional"],
    instructions:
      "Usa solo la cantidad de salsa picante que apetezca. Añade proteína y guisantes para que no sea solo noodles; no compenses después.",
    tags: ["antojo", "asiático", "15 minutos", "crujiente"],
    slots: ["lunch", "dinner"],
    active: true,
  },
  {
    id: "frozen-rice-protein",
    name: "Arroz congelado, proteína y salsa en cubos",
    shortName: "Arroz de emergencia",
    kind: "emergency",
    baseKcal: 640,
    baseProteinG: 35,
    baseFibreG: 11,
    baseGrams: 510,
    ingredients: [
      "arroz blanco congelado",
      "Garden Gourmet, tofu o seitán",
      "guisantes u otra verdura congelada",
      "2–3 cubos de curry o tomate",
    ],
    instructions: "Air fryer para la proteína; microondas para arroz, verduras y salsa. Todo listo en unos 12 minutos.",
    tags: ["12 minutos", "congelador", "emergencia"],
    slots: ["lunch", "dinner"],
    active: true,
  },
  {
    id: "noodles-tofu",
    name: "Noodles de despensa con tofu y verduras",
    shortName: "Noodles rápidos",
    kind: "emergency",
    baseKcal: 660,
    baseProteinG: 36,
    baseFibreG: 10,
    baseGrams: 520,
    ingredients: ["noodles", "tofu o huevo", "guisantes", "salsa de soja", "cubos de salsa de verduras"],
    instructions: "Hierve los noodles y termina todo en la misma olla. Añade chile por separado para que cada persona elija.",
    tags: ["15 minutos", "despensa", "asiático"],
    slots: ["lunch", "dinner"],
    active: true,
  },
  {
    id: "meal-out",
    name: "Comida fuera sin compensación",
    shortName: "Comer fuera",
    kind: "flex",
    baseKcal: 900,
    baseProteinG: 30,
    baseFibreG: 8,
    baseGrams: 600,
    ingredients: ["Elige lo que os apetezca", "agua si os sienta bien", "sin ayuno ni cardio de castigo después"],
    instructions: "Registra una estimación solo si ayuda. La siguiente comida es normal: proteína, fibra, hidrato y algo que esté rico.",
    tags: ["flexible", "fuera", "sin castigo"],
    slots: ["lunch", "dinner"],
    active: true,
  },
];

export const DEFAULT_STATE: AppState = {
  version: 1,
  profiles: {
    adrian: {
      id: "adrian",
      name: "Adrián",
      color: "#62a8ff",
      sexAtBirth: "male",
      age: 27,
      heightCm: 180,
      weightKg: 95,
      goal: "recomposition",
      goalDeltaKcal: -100,
      minimumKcal: 2300,
      maximumKcal: 2900,
      proteinTargetG: 150,
      fibreTargetG: 40,
      waterTargetMl: 2000,
      mealSplit: { breakfast: 0.17, lunch: 0.32, snack: 0.16, dinner: 0.35 },
      wakeTime: "07:00",
      sleepTime: "00:00",
      notes: [
        "Ovolactovegetariano",
        "Hígado graso y acidez: evitar cambios extremos y comidas gigantes frecuentes",
        "Fatiga y somnolencia pendientes de revisar con un profesional",
      ],
    },
    rali: {
      id: "rali",
      name: "Rali",
      color: "#f08db7",
      sexAtBirth: "female",
      age: 26,
      heightCm: 160,
      weightKg: 95,
      goal: "weight-loss",
      goalDeltaKcal: -300,
      minimumKcal: 1700,
      maximumKcal: 2100,
      proteinTargetG: 105,
      fibreTargetG: 32,
      waterTargetMl: 2000,
      mealSplit: { breakfast: 0.15, lunch: 0.38, snack: 0.15, dinner: 0.32 },
      wakeTime: "11:00",
      sleepTime: "03:30",
      notes: [
        "Ovolactovegetariana",
        "Verduras cocinadas y preferiblemente trituradas; nada de pimiento",
        "Nada de cebolla cruda",
        "Priorizar sabor, textura, queso, curry, tomate y crujiente para facilitar comer",
      ],
    },
  },
  activities: [
    {
      id: "adrian-work-morning",
      personId: "adrian",
      label: "Trabajo de mañana",
      category: "work",
      days: [1, 2, 3, 4, 5, 6],
      start: "08:00",
      end: "14:00",
      enabled: true,
      energyMode: "met",
      met: 1.6,
      fixedKcal: 0,
      notes: "Regla semanal importada del patrón de Quedamos.",
    },
    {
      id: "adrian-work-afternoon",
      personId: "adrian",
      label: "Segundo turno",
      category: "work",
      days: [2, 3, 4],
      start: "16:30",
      end: "18:30",
      enabled: true,
      energyMode: "met",
      met: 1.6,
      fixedKcal: 0,
    },
    {
      id: "adrian-walk-out",
      personId: "adrian",
      label: "Ir andando al trabajo",
      category: "walk",
      days: [1, 2, 3, 4, 5, 6],
      start: "07:25",
      end: "08:00",
      enabled: true,
      energyMode: "met",
      met: 3.3,
      fixedKcal: 0,
      notes: "Desactívalo cuando vuelvas a usar la bici.",
    },
    {
      id: "adrian-walk-home",
      personId: "adrian",
      label: "Volver andando",
      category: "walk",
      days: [1, 2, 3, 4, 5, 6],
      start: "14:00",
      end: "14:35",
      enabled: true,
      energyMode: "met",
      met: 3.3,
      fixedKcal: 0,
    },
  ],
  activityOverrides: {},
  mealTemplates: DEFAULT_MEALS,
  scenarios: {},
  feedback: [],
  weightLogs: [],
  waterLogs: {},
  supplements: [
    {
      id: "adrian-creatine",
      personId: "adrian",
      label: "Creatina",
      note: "Según la pauta que decidáis; la constancia importa más que la hora.",
      enabled: true,
    },
    {
      id: "adrian-omega3",
      personId: "adrian",
      label: "Omega-3 vegano",
      note: "Usar la dosis de la etiqueta cuando confirméis EPA/DHA.",
      enabled: true,
    },
    {
      id: "rali-omega3",
      personId: "rali",
      label: "Omega-3 vegano",
      note: "Usar la dosis de la etiqueta cuando confirméis EPA/DHA.",
      enabled: true,
    },
  ],
  dailyChecks: {},
  settings: {
    timezone: "Europe/Madrid",
    cookCycleAnchor: "2026-09-28",
    batchLunchTemplateId: "tvp-beans-tomato",
    batchDinnerTemplateId: "tofu-pea-curry",
    selectedPerson: "adrian",
  },
};

export function freshDefaultState(): AppState {
  return JSON.parse(JSON.stringify(DEFAULT_STATE)) as AppState;
}
